export default strategy({
  name: "Cofre Sete V1",

  dependencies: {
    runner: strategyLibrary("cofre-sete-runner", 1),
  },

  params: {
    walletSize: 100,
    entryWindowStart: 118,
    entryWindowEnd: 3,
    maxEventExposure: 36,
    maxEntryValue: 8,
    minShares: 4,
    maxEntriesPerEvent: 8,
    cooldownSec: 5,
    minAsk: 0.035,
    maxAsk: 0.74,
    minEdge: 0.085,
    minDirectionalProb: 0.61,
    minDistanceAbs: 60,
    minSigma: 8,
    sigmaMultiplier: 1,
    modelWeight: 0.66,
    driftWeight: 0.42,
    driftClampSigma: 0.9,
    accelerationWeight: 0.28,
    bookImbalanceWeight: 0.2,
    momentumSec: 7,
    slowMomentumSec: 26,
    slowMomentumWeight: 0.28,
    volLookbackSec: 55,
    maxSpread: 0.1,
    maxOddsSum: 1.2,
    minOddsSum: 0.8,
    entrySlippageMax: 0.02,
    minLiquidityRatio: 0.68,
    fallbackBookSize: 0,
    kellyFraction: 0.15,
    maxKellyPct: 0.2,
    riskBudgetPct: 0.45,
    maxWorstLossAbs: 45,
    vaultBoxEnabled: true,
    boxMaxSumAsk: 0.992,
    boxMinProfit: 0.008,
    boxMaxPairValue: 15,
    hedgeEnabled: false,
    hedgeMaxAsk: 0.6,
    hedgeMinLockedProfit: 0.08,
    hedgeMinWorstCaseImprovement: 0.65,
    maxHedgesPerEvent: 2,
    trapEnabled: false,
    trapMaxValue: 4,
    trapMinCheapAsk: 0.04,
    trapMaxCheapAsk: 0.34,
    trapMinExpensiveBid: 0.68,
    trapMaxDistanceAbs: 125,
    trapMinDecelZ: 0.2,
    trapMinEdge: -0.04,
    takeProfitBid: 0.9,
    takeProfitPct: 0.35,
    trailAfterBid: 0.76,
    trailDrop: 0.14,
    stopBid: 0.12,
    edgeExitBelow: -0.06,
    lateExitSec: 7,
    lateExitMinBid: 0.64,
    protectedExitSkipProfit: 0.04,
    minTicksBeforeEntry: 8,
  },

  onEventStart() {},

  onTick() {},

  onEventEnd() {},
});