export default strategy({
  name: "Pair Ladder Complete-Set V1",

  dependencies: {
    runner: strategyLibrary("pair-ladder-complete-set-runner", 1),
  },

  params: {
    walletSize: 100,
    mode: "clip_ladder",
    openShares: 50,
    clipShares: 100,
    openMinAsk: 0.45,
    openMaxAsk: 0.55,
    openMaxAvgSum: 1.0,
    maxSecToOpen: 20,
    minSecondsLeftToEnter: 15,
    stopAvgSum: 0.98,
    stopMinBalance: 0.95,
    blockAvgSum: 1.02,
    maxResidualShares: 50,
    pairSnapMax: 0.97,
    rebalanceSlackCents: 3,
    buildOnlyImprove: true,
    buildMaxAvgSum: 1.0,
    lateStartSec: 180,
    lateMaxAsk: 0.12,
    lateUltraAsk: 0.05,
    lateClipShares: 50,
    lateUltraClipShares: 20,
    lateOnlyImprove: true,
    maxEventNotional: 250,
    maxSharesPerSide: 400,
    maxFillsPerEvent: 40,
    sprayOpenShares: 20,
    sprayClipShares: 10,
    sprayMaxFillsPerEvent: 200,
    takerFeeRate: 0.07,
    spreadCents: 1,
    slippageCents: 0,
    requireQuality: true,
    minCoverage: 0.99,
    applyPolymarketFees: true,
    polymarketFeeCategory: "crypto",
  },

  onEventStart() {},
  onTick() {},
  onEventEnd() {},
});
