export default strategy({
  name: "Momentum Edge V1",

  dependencies: {
    runner: strategyLibrary("momentum-edge-runner", 1),
  },

  params: {
    walletSize: 100,
    maxOrderValue: 5,
    minShares: 1,
    entryWindowStart: 297,
    entryWindowEnd: 0,
    warmupSec: 3,
    minAsk: 0.31,
    maxAsk: 0.85,
    minEdge: 0.03,
    maxSpread: 0.05,
    minDirectionalProb: 0.51,
    minProbHighAsk: 0.51,
    minDistanceAbs: 13,
    inversionDistanceAbs: 15,
    askSemEdge: 0.65,
    entrySlippageMax: 0.02,
    minLiquidityRatio: 1,
    minSigma: 30,
    sigmaMultiplier: 1,
    distanceWeight: 1.8,
    momentumWeight: 1.2,
    lagWeight: 0.9,
    fastMomentumSec: 10,
    slowMomentumSec: 30,
    slowMomentumWeight: 0.4,
    historyWindowSec: 120,
    oddsSumTolerance: 0.2,
    fallbackExitBid: 0.01,
    inversionSharesMultiplier: 2,
    deteriorationEnabled: true,
    inversionEnabled: true,
    deteriorationOddFactor: 0.45,
    deteriorationProbFactor: 0.45,
    deteriorationRequiresCross: true,
    dynamicEdgeEnabled: true,
    edgeTier1MaxAsk: 0.35,
    edgeTier1Min: 0.06,
    edgeTier2MaxAsk: 0.5,
    edgeTier2Min: 0.03,
    edgeTier3MaxAsk: 0.65,
    edgeTier3Min: 0.01,
    edgeTier4MaxAsk: 0.75,
    edgeTier4Min: -0.03,
    edgeTier5Min: -0.08,
    positionSizingMode: "bankroll",
    minStake: 1,
    bankrollThreshold: 100,
    bankrollPct: 0.05,
    reinforcementEnabled: true,
    reinforcementDistanceFactor: 1.36,
    reinforcementShares: 0,
    reinforcementStakeMultiplier: 1,
    postInversionStopLossEnabled: true,
    postInversionStopLossFactor: 0.5,
    postInversionReentryShares: 0,
    postInversionReentryMultiplier: 2,
    postInversionReentryStakeMultiplier: 4,
    allowedPositionSide: "BOTH",
    entryShares: 0,
    reversalShares: 0,
    strategyName: "MOMENTUM_EDGE_MODEL_V1",
    strategyDisplayName: "Momentum Edge Model V1",
  },

  onEventStart() {},

  onTick() {},

  onEventEnd() {},
});

