export default strategy({
  name: "Clip-Path V1",

  dependencies: {
    runner: strategyLibrary("pair-path-runner", 1),
  },

  params: {
    walletSize: 100,
    openShares: 10,
    openAskLo: 0.52,
    openAskHi: 0.62,
    openTriggerCents: 55,
    openCapCents: 2,
    avgSumMax: 0.94,
    eqAvgSumMax: 0.97,
    hedgeAskMax: 0.4,
    tauOpenMin: 40,
    tauOpenMax: 240,
    tauHedgeMin: 15,
    tauEqMin: 8,
    eqAskMax: 0.05,
    legChoice: "chase",
    hedgeCapCents: 1,
    maxOpenAttempts: 3,
    maxHedgeAttempts: 8,
    makerTimeoutSec: 30,
    feeRate: 0.07,
    maxEventNotional: 16,
    restingFillModel: "none",
    confirmationTicks: 2,
    maxClipsPerTick: 1,
    hedgeLevels: [
      { askMax: 0.4, frac: 0.4 },
      { askMax: 0.36, frac: 0.3 },
      { askMax: 0.32, frac: 0.3 },
    ],
    tauHedgeEscape: 20,
    hedgeEscapeAskMax: 0.42,
    escapeAvgSumMax: 0.98,
    escapeMinLockedPnlPerShare: -0.02,
    tauHedgeEscape2: 12,
    hedgeEscapeAskMax2: 0.45,
    escapeAvgSumMax2: 1.0,
    escapeMinLockedPnlPerShare2: -0.04,
    openRequireHedgeReady: false,
    applyPolymarketFees: true,
    polymarketFeeCategory: "crypto",
    requireQuality: true,
    minCoverage: 0.99,
  },

  onEventStart() {},
  onTick() {},
  onEventEnd() {},
});
