import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export function createLabReportDir({ strategyId, experimentName, root = 'reports/labs' }) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safeExperiment = slugPart(experimentName || 'experiment');
  const dir = path.resolve(root, slugPart(strategyId), `${timestamp}-${safeExperiment}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

export function writeLabReport(reportDir, report) {
  writeJson(path.join(reportDir, 'experiment.json'), report.experiment);
  writeJson(path.join(reportDir, 'results.json'), report.results);
  writeJson(path.join(reportDir, 'top-results.json'), report.topResults);
  writeJson(path.join(reportDir, 'metadata.json'), report.metadata);
  writeFileSync(path.join(reportDir, 'summary.md'), renderSummaryMarkdown(report), 'utf8');
}

export function gitMetadata() {
  return {
    commit: safeGit(['rev-parse', 'HEAD']),
    shortCommit: safeGit(['rev-parse', '--short', 'HEAD']),
    branch: safeGit(['branch', '--show-current']),
    dirty: safeGit(['status', '--short']) ? true : false,
  };
}

function writeJson(file, data) {
  writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function safeGit(args) {
  try {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return null;
  }
}

function slugPart(value) {
  return String(value || 'unknown')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'unknown';
}

function renderSummaryMarkdown(report) {
  const { metadata, results, topResults } = report;
  const timings = results.timings || {};
  const lines = [
    `# ${metadata.experimentName}`,
    '',
    `- Strategy: \`${metadata.strategyId}\``,
    `- Window: \`${metadata.window.from}\` -> \`${metadata.window.to}\``,
    `- Dataset: \`${metadata.dataset}\``,
    `- Variants: ${metadata.variantCount}${metadata.truncated ? ` / ${metadata.totalVariantCount} planned` : ''}`,
    `- Ticks: ${results.ticks ?? 'n/a'}`,
    `- DuckDB read: ${timings.duckdbReadMs ?? 'n/a'} ms`,
    `- Sweep process: ${timings.sweepProcessMs ?? 'n/a'} ms`,
    `- Total: ${timings.totalMs ?? 'n/a'} ms`,
    `- Avg variant: ${timings.avgVariantMs ?? 'n/a'} ms`,
    '',
    '## Top Results',
    '',
    '| Rank | Variant | PnL | Entries | Win % | PF | Max DD | Pos Days | Worst Day | Variant ms |',
    '|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|',
  ];

  for (const item of topResults.slice(0, 20)) {
    lines.push([
      `| ${item.rank}`,
      `\`${item.id}\``,
      formatNumber(item.summary.totalPnl),
      item.summary.entries ?? 0,
      formatNumber(item.summary.winRate),
      formatNumber(item.summary.profitFactor),
      formatNumber(item.summary.maxDrawdown),
      item.summary.daily ? `${item.summary.daily.profitableDays}/${item.summary.daily.days}` : 'n/a',
      item.summary.daily ? formatNumber(item.summary.daily.worstDayPnl) : 'n/a',
      item.variantMs ?? 'n/a',
      '|',
    ].join(' | '));
  }

  lines.push('', '## Notes', '', '- Generated by `npm run lab:run`.');
  return `${lines.join('\n')}\n`;
}

function formatNumber(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) return '0';
  return String(Math.round(number * 10000) / 10000);
}
